[book]
authors = ["Primordium Contributors"]
language = "en"
src = "src"
title = "Primordium Technical Manual"

[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true

[output.html]
git-repository-url = "https://github.com/pplmx/primordium"
